version: '3.8'

services:
  # Backend API Service
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: dial-craft-backend
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./dev.db
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-change-in-production-32-chars-minimum}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-1h}
      - JWT_REFRESH_EXPIRES_IN=${JWT_REFRESH_EXPIRES_IN:-7d}
      - PORT=3000
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:8080}
    volumes:
      - backend_data:/app/prisma
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - dial-craft-network

  # Frontend Service  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dial-craft-frontend
    ports:
      - "3000:80"
    environment:
      - NGINX_PORT=80
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - dial-craft-network

volumes:
  backend_data:
    driver: local

networks:
  dial-craft-network:
    driver: bridge